theme: jekyll-theme-minimal
logo: /assets/colin-pro-rnd2.png
title: 200 Meters
description: <br><br><br>In road cycling 200 meters marks the start of the final sprint and the culmination of the race. It's where innovation, preparation, strategy, and luck come together. This site hosts current projects and ideas bringing together technology, policy, design, and agility.  
show_downloads: false
google_analytics:
permalink: /blog/:year/:month/:day/:title
